// Pokemon banned from the Fasher Draft League Season 3 format.
// To ban or unban something, just add or remove its name below (must match
// how the Pokemon's name appears in the dex, e.g. "Rayquaza-Mega").
export const FasherDraftBanlist: string[] = [
	// All AG Mons are Banned
	'Calyrex-Shadow',
	'Koraidon',
	'Miraidon',
	'Rayquaza-Mega',
	'Xerneas',

	// Banned Ubers
	'Arceus',
	'Arceus-Bug',
	'Arceus-Dark',
	'Arceus-Dragon',
	'Arceus-Electric',
	'Arceus-Fairy',
	'Arceus-Fighting',
	'Arceus-Fire',
	'Arceus-Flying',
	'Arceus-Ghost',
	'Arceus-Grass',
	'Arceus-Ground',
	'Arceus-Ice',
	'Arceus-Poison',
	'Arceus-Psychic',
	'Arceus-Rock',
	'Arceus-Steel',
	'Arceus-Water',
	'Blastoise-Mega',
	'Blaziken-Mega',
	'Calyrex-Ice',
	'Chien-Pao',
	'Darmanitan-Galar',
	'Deoxys-Normal',
	'Deoxys-Attack',
	'Dialga',
	'Dialga-Origin',
	'Dracovish',
	'Eternatus',
	'Flutter Mane',
	'Genesect',
	'Genesect-Burn',
	'Genesect-Chill',
	'Genesect-Douse',
	'Genesect-Shock',
	'Gengar-Mega',
	'Giratina',
	'Giratina-Origin',
	'Groudon',
	'Groudon-Primal',
	'Ho-Oh',
	'Kyogre',
	'Kyogre-Primal',
	'Kyurem-Black',
	'Kyurem-White',
	'Lucario-Mega',
	'Lugia',
	'Lunala',
	'Magearna',
	'Magearna-Original',
	'Marshadow',
	'Mewtwo',
	'Mewtwo-Mega-X',
	'Mewtwo-Mega-Y',
	'Naganadel',
	'Necrozma-Dawn-Wings',
	'Necrozma-Dusk-Mane',
	'Necrozma-Ultra',
	'Palkia',
	'Palkia-Origin',
	'Pheromosa',
	'Rayquaza',
	'Reshiram',
	'Salamence-Mega',
	'Shaymin-Sky',
	'Solgaleo',
	'Spectrier',
	'Terapagos-Stellar',
	'Yveltal',
	'Zacian',
	'Zacian-Crowned',
	'Zamazenta',
	'Zamazenta-Crowned',
	'Zekrom',
	'Zygarde-Complete',

	// Other Banned Mons
	'Unown',
	'Shedinja',

	// New Megas - Unreleased
	'Garchomp-Mega-Z',
	'Golisopod-Mega',
	'Heatran-Mega',
	'Lucario-Mega-Z',
	'Magearna-Mega',
	'Tatsugiri-Mega',
	'Zeraora-Mega',

	// Banned Megas
	'Latias-Mega',
	'Metagross-Mega',
	'Raichu-Mega-Y',

];
