// Pokemon banned from using Tera in the Fasher Draft League Season 3 format.
// To ban or unban something, just add or remove its name below (must match
// how the Pokemon's name appears in the dex, e.g. "Rayquaza-Mega"). Note
// that a Pokemon's default forme has no suffix - "Enamorus" is Incarnate
// Forme, not "Enamorus-Incarnate".
export const FasherTeraBanlist: string[] = [
	'Baxcalibur',
	'Blaziken',
	'Chi-Yu',
	'Darkrai',
	'Deoxys-Speed',
	'Dragonite',
	'Enamorus',
	'Espathra',
	'Garchomp',
	'Gouging Fire',
	'Iron Boulder',
	'Iron Bundle',
	'Iron Valiant',
	'Kingambit',
	'Kyurem',
	'Latias',
	'Latios',
	'Ogerpon-Hearthflame',
	'Palafin',
	'Regieleki',
	'Roaring Moon',
	'Sneasler',
	'Terapagos',
	'Ursaluna-Bloodmoon',
	'Volcarona',

	// Megas are unable to Terastalize
	'Abomasnow-Mega',
	'Absol-Mega',
	'Absol-Mega-Z',
	'Aerodactyl-Mega',
	'Aggron-Mega',
	'Alakazam-Mega',
	'Altaria-Mega',
	'Ampharos-Mega',
	'Audino-Mega',
	'Banette-Mega',
	'Barbaracle-Mega',
	'Baxcalibur-Mega',
	'Beedrill-Mega',
	'Blastoise-Mega',
	'Blaziken-Mega',
	'Camerupt-Mega',
	'Chandelure-Mega',
	'Charizard-Mega-X',
	'Charizard-Mega-Y',
	'Chesnaught-Mega',
	'Chimecho-Mega',
	'Clefable-Mega',
	'Crabominable-Mega',
	'Crucibelle-Mega',
	'Darkrai-Mega',
	'Delphox-Mega',
	'Diancie-Mega',
	'Dragalge-Mega',
	'Dragonite-Mega',
	'Drampa-Mega',
	'Eelektross-Mega',
	'Emboar-Mega',
	'Excadrill-Mega',
	'Falinks-Mega',
	'Feraligatr-Mega',
	'Floette-Mega',
	'Froslass-Mega',
	'Gallade-Mega',
	'Garchomp-Mega',
	'Garchomp-Mega-Z',
	'Gardevoir-Mega',
	'Gengar-Mega',
	'Glalie-Mega',
	'Glimmora-Mega',
	'Golisopod-Mega',
	'Golurk-Mega',
	'Greninja-Mega',
	'Gyarados-Mega',
	'Hawlucha-Mega',
	'Heatran-Mega',
	'Heracross-Mega',
	'Houndoom-Mega',
	'Kangaskhan-Mega',
	'Latias-Mega',
	'Latios-Mega',
	'Lopunny-Mega',
	'Lucario-Mega',
	'Lucario-Mega-Z',
	'Magearna-Mega',
	'Magearna-Original-Mega',
	'Malamar-Mega',
	'Manectric-Mega',
	'Mawile-Mega',
	'Medicham-Mega',
	'Meganium-Mega',
	'Meowstic-F-Mega',
	'Meowstic-M-Mega',
	'Metagross-Mega',
	'Mewtwo-Mega-X',
	'Mewtwo-Mega-Y',
	'Pidgeot-Mega',
	'Pinsir-Mega',
	'Pyroar-Mega',
	'Raichu-Mega-X',
	'Raichu-Mega-Y',
	'Rayquaza-Mega',
	'Sableye-Mega',
	'Salamence-Mega',
	'Sceptile-Mega',
	'Scizor-Mega',
	'Scolipede-Mega',
	'Scovillain-Mega',
	'Scrafty-Mega',
	'Sharpedo-Mega',
	'Skarmory-Mega',
	'Slowbro-Mega',
	'Staraptor-Mega',
	'Starmie-Mega',
	'Steelix-Mega',
	'Swampert-Mega',
	'Tatsugiri-Curly-Mega',
	'Tatsugiri-Droopy-Mega',
	'Tatsugiri-Stretchy-Mega',
	'Tyranitar-Mega',
	'Venusaur-Mega',
	'Victreebel-Mega',
	'Zeraora-Mega',
	'Zygarde-Mega',
];
